name: flutter_movie
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


  #Core
  equatable: ^2.0.5 

  #Network 
  vexana: ^3.5.4
  cached_network_image: ^3.3.1

  #Config
  envied: ^0.5.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  #Utiliy
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1

  widgets: 
    path: module/widgets
  lottie: ^2.7.0
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter


  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0
  envied_generator: ^0.5.3
  flutter_gen_runner: ^5.4.0


flutter_gen:
  output: lib/gen/asset
  integrations:
    lottie: true
    flutter_svg: true



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lottie/
    - assets/icons/
    - assets/image/
    - assets/colors/
    - assets/colors/
    
    


