name: flutter_movie
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Core 
  vexana: ^3.5.4
  kartal: ^3.5.0
  equatable: ^2.0.5 
  json_annotation: ^4.8.1
  envied: ^0.5.3

  cupertino_icons: ^1.0.2

  easy_logger: ^0.0.2
  logger: ^2.0.2+1

  widgets: 
    path: module/widgets


dev_dependencies:
  flutter_test:
    sdk: flutter


  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0


flutter_gen:
  output: lib/product/gene
  integrations:
    lottie: true



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


